environment = "dev"
intervals {
    poll = 1 hour
    storage = 60 days
}
price-feeds = [
    {
        token-pair = "DAG_USD"
        gateio-ticker = "DAG_USDT"
        kucoin-ticker = "DAG-USDT"
        mexc-ticker = "DAGUSDT"
    }
]
